=== zeeshan123abbas/ACCP_AI_7144/Term-2-DISM/01-Data-Processing-with-XML-and-JSON/Session-02-Namespaces-and-DTD/products.dtd
<!-- products.dtd : shared rules for product catalogues -->
<!ELEMENT catalog (product*)>
<!ELEMENT product (name, price, stock, tags?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT stock (#PCDATA)>
<!ELEMENT tags (tag+)>
<!ELEMENT tag (#PCDATA)>
<!ATTLIST product
    code ID #REQUIRED
    available (yes|no) "yes">

=== zeeshan123abbas/ACCP_AI_7144/Term-2-DISM/01-Data-Processing-with-XML-and-JSON/Session-02-Namespaces-and-DTD/products.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalog SYSTEM "products.dtd">
<catalog>
  <product code="P100">
    <name>USB-C Charger</name>
    <price>2500</price>
    <stock>40</stock>
    <tags><tag>mobile</tag><tag>accessory</tag></tags>
  </product>
  <product code="P101" available="no">
    <name>Laptop Stand</name>
    <price>4200</price>
    <stock>0</stock>
  </product>
</catalog>
